### PR TITLE
Dictionary and python3 fix.

### PR DESCRIPTION
**Pull request by tommyjcarpenter**
This addresses https://github.com/debrouwere/facebook-insights/issues/2. In short, this solves a "RuntimeError: dictionary changed size during iteration" error and a Python3 error because urllib changed in python3.

### CODE REVIEW

**Comment by tommyjcarpenter** [comment]
This code is now only Python3 compatible. If this code is supposed to support 2 and 3, we may have to do something fancier. Regardless the dictionary piece is broken.

**Comment by tommyjcarpenter** [comment]
Actually, I realized you had a really nice urllib trick in another file; I've used that trick in the new file and rebased.

**Comment by tommyjcarpenter** [comment]
@debrouwere can we push this to pypi?

**Comment by debrouwere** [comment]
Done!

**Comment by tommyjcarpenter** [comment]
Thanks!! We depend on this package here at SumAll =)

**Comment by debrouwere** [comment]
Cool :-)

**Pull request merged**
